apiVersion: apps/v1
kind: Deployment
metadata: 
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth # tell the cluster the math "name" in metadata to deploy
  template: 
    metadata:
      labels: 
        app: auth 
    spec: 
      containers: 
        - name: auth 
          image: willnguyen/auth
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef: 
                  name: jwt-secret
                  key: JWT_KEY

---
apiVersion: v1 
kind: Service 
metadata: 
  name: auth-srv
spec: 
  selector: 
    app: auth
  ports: 
    - name: auth
      protocol: TCP
      port: 3000 
      targetPort: 3000
  
